version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "deps"
    # Disable version updates and only allow security updates
    open-pull-requests-limit: 0
    reviewers:
      - "City-of-Helsinki/kuva-backend"
      - "City-of-Helsinki/kuva-developers"
      - "City-of-Helsinki/ratkaisutoimiston-backend"
