# Pre-commit hook documentation:
# - https://pre-commit.com/
# - https://pre-commit.com/hooks.html
#
# Ruff pre-commit hook documentation:
# - https://github.com/astral-sh/ruff-pre-commit
default_language_version:
  python: python3.12
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # NOTE: Don't move the trailing "ruff-pre-commit version" comment from
    # the ruff's version line, it is used by test_pre_commit_ruff_version.py
    # test case in order not to have to add a YAML library dependency just
    # to test this version:
    rev: v0.9.10 # ruff-pre-commit version
    hooks:
      # Run the linter
      - id: ruff
        args: [ --fix ]
      # Run the formatter
      - id: ruff-format
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.0.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: []
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1
    hooks:
      - id: gitlint
        stages: [commit-msg]
  - repo: https://github.com/frnmst/md-toc
    rev: 9.0.0
    hooks:
      - id: md-toc
        # Skip first line to exclude topmost heading from Table of Contents
        args: ['--in-place', '--newline-string=\n', '--skip-lines=1', 'github']
