# Pre-commit hook documentation:
# - https://pre-commit.com/
# - https://pre-commit.com/hooks.html
#
# Ruff pre-commit hook documentation:
# - https://github.com/astral-sh/ruff-pre-commit
default_language_version:
  python: python3.11
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version
    rev: v0.6.9
    hooks:
      # Run the linter
      - id: ruff
        args: [ --fix ]
      # Run the formatter
      - id: ruff-format
