default_language_version:
    python: python3
default_install_hook_types: [pre-commit, commit-msg]
default_stages: [pre-commit, manual]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        exclude: ^.*\.ambr$
      - id: end-of-file-fixer
        exclude: notification_importers/templates/sms/
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
        exclude: ^.*\.ambr$
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # NOTE: Don't move the trailing "ruff-pre-commit version" comment from
    # the ruff's version line, it is used by test_pre_commit_ruff_version.py
    # test case in order not to have to add a YAML library dependency just
    # to test this version:
    rev: v0.13.2 # ruff-pre-commit version
    hooks:
      # Run the linter
      - id: ruff
        args: [ --fix ]
      # Run the formatter
      - id: ruff-format
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.22.0
    hooks:
      - id: commitlint
        stages: [ commit-msg, manual ]
        additional_dependencies: [ "@commitlint/config-conventional" ]
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.11.0
    hooks:
      - id: shellcheck
  - repo: https://github.com/frnmst/md-toc
    rev: 9.0.0
    hooks:
      - id: md-toc
        # Skip first line to exclude topmost heading from Table of Contents
        args: ['--in-place', '--newline-string=\n', '--skip-lines=1', 'github']
