services:
    kultus-db:
        image: postgres:17-alpine
        restart: on-failure
        env_file:
            - .env  # For POSTGRES_USER, POSTGRES_PASSWORD and POSTGRES_DB
        ports:
            - ${DB_PORT:-5434}:5432
        volumes:
            - pgdata:/var/lib/postgresql/data
        container_name: kultus-db

    django:
        build:
            context: .
            target: ${DOCKER_TARGET:-development}  # stage of Dockerfile to build
        env_file:
            - .env
        volumes:
            - .:/app
        ports:
            - 8081:8081
            - 8000:8000
        depends_on:
            - kultus-db
        container_name: kultus-backend

volumes:
    pgdata:
        driver: local

networks:
    default:
        name: helsinki
