services:
    kultus-db:
        image: postgres:13
        restart: on-failure
        environment:
            POSTGRES_USER: kultus
            POSTGRES_PASSWORD: kultus
            POSTGRES_DB: kultus
        ports:
            - ${DB_PORT:-5434}:5432
        volumes:
            - pgdata:/var/lib/postgresql@13/data
        container_name: kultus-db

    django:
        build:
            context: .
            target: ${DOCKER_TARGET:-development}
        env_file:
            - docker-compose.env.yaml
        environment:
            DATABASE_URL: postgres://kultus:kultus@kultus-db/kultus
            DATABASE_HOST: kultus-db.helsinki
        volumes:
            - .:/app
        ports:
            - 8081:8081
            - 8000:8000
        depends_on:
            - kultus-db
        container_name: kultus-backend

volumes:
    pgdata:
        driver: local

networks:
    default:
        name: helsinki
