# Common errors
GENERAL_ERROR = "GENERAL_ERROR"
PERMISSION_DENIED_ERROR = "PERMISSION_DENIED_ERROR"
OBJECT_DOES_NOT_EXIST_ERROR = "OBJECT_DOES_NOT_EXIST_ERROR"
DATA_VALIDATION_ERROR = "DATA_VALIDATION_ERROR"
API_USAGE_ERROR = "API_USAGE_ERROR"
QUERY_TOO_DEEP_ERROR = "QUERY_TOO_DEEP_ERROR"
