# Generated by Django 2.2.13 on 2021-01-26 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0004_person_language"),
        ("verification_token", "0001_add_verification_token"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="verificationtoken",
            name="user",
        ),
        migrations.AddField(
            model_name="verificationtoken",
            name="person",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="organisations.Person",
            ),
        ),
    ]
