# Generated by Django 2.2.10 on 2020-04-29 09:17

import django.db.models.deletion
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Enrolment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enrolment_time", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "enrolment",
                "verbose_name_plural": "enrolments",
            },
        ),
        migrations.CreateModel(
            name="Occurrence",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated_at"),
                ),
                (
                    "linked_event_id",
                    models.CharField(max_length=255, verbose_name="linked event id"),
                ),
                (
                    "min_group_size",
                    models.PositiveSmallIntegerField(verbose_name="min group size"),
                ),
                (
                    "max_group_size",
                    models.PositiveSmallIntegerField(verbose_name="max group size"),
                ),
                ("start_time", models.DateTimeField(verbose_name="start time")),
                ("end_time", models.DateTimeField(verbose_name="end time")),
            ],
            options={
                "verbose_name": "occurrence",
                "verbose_name_plural": "occurrences",
            },
        ),
        migrations.CreateModel(
            name="StudyGroup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated_at"),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=1000, verbose_name="name"),
                ),
                (
                    "group_size",
                    models.PositiveSmallIntegerField(verbose_name="group size"),
                ),
            ],
            options={
                "verbose_name": "study group",
                "verbose_name_plural": "study groups",
            },
        ),
        migrations.CreateModel(
            name="VenueCustomData",
            fields=[
                (
                    "place_id",
                    models.CharField(
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                        verbose_name="place id",
                    ),
                ),
            ],
            options={
                "verbose_name": "venue custom data",
                "verbose_name_plural": "venue custom data",
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="VenueCustomDataTranslation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        db_index=True, max_length=15, verbose_name="Language"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "master",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="occurrences.VenueCustomData",
                    ),
                ),
            ],
            options={
                "verbose_name": "venue custom data Translation",
                "db_table": "occurrences_venuecustomdata_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
            },
        ),
    ]
