# Generated by Django 2.2.10 on 2020-04-29 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organisations", "0001_initial"),
        ("occurrences", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studygroup",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="organisations.Person",
                verbose_name="person",
            ),
        ),
        migrations.AddField(
            model_name="occurrence",
            name="contact_persons",
            field=models.ManyToManyField(
                blank=True,
                related_name="occurrences",
                to="organisations.Person",
                verbose_name="contact persons",
            ),
        ),
        migrations.AddField(
            model_name="occurrence",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                related_name="occurrences",
                through="occurrences.Enrolment",
                to="occurrences.StudyGroup",
                verbose_name="group",
            ),
        ),
        migrations.AddField(
            model_name="occurrence",
            name="organisation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="organisations.Organisation",
                verbose_name="organisation",
            ),
        ),
        migrations.AddField(
            model_name="enrolment",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrolments",
                to="occurrences.StudyGroup",
                verbose_name="study group",
            ),
        ),
        migrations.AddField(
            model_name="enrolment",
            name="occurrence",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrolments",
                to="occurrences.Occurrence",
                verbose_name="occurrences",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="venuecustomdatatranslation",
            unique_together={("language_code", "master")},
        ),
        migrations.AddConstraint(
            model_name="enrolment",
            constraint=models.UniqueConstraint(
                fields=("group", "occurrence"), name="unq_group_occurrence"
            ),
        ),
    ]
