# Generated by Django 2.2.10 on 2020-05-13 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("occurrences", "0002_alter_fields"),
    ]
    operations = [
        migrations.CreateModel(
            name="PalvelutarjotinEvent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated_at"),
                ),
                (
                    "linked_event_id",
                    models.CharField(max_length=255, verbose_name="linked event id"),
                ),
                (
                    "enrolment_start",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="enrolment start"
                    ),
                ),
                (
                    "enrolment_end",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="enrolment end"
                    ),
                ),
                ("duration", models.PositiveSmallIntegerField(verbose_name="duration")),
                (
                    "needed_occurrences",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="needed occurrence"
                    ),
                ),
            ],
            options={
                "verbose_name": "palvelutarjotin event",
                "verbose_name_plural": "palvelutarjotin events",
            },
        ),
        migrations.RemoveField(model_name="occurrence", name="linked_event_id",),
        migrations.AddField(
            model_name="occurrence",
            name="place_id",
            field=models.CharField(blank=True, max_length=255, verbose_name="place id"),
        ),
        migrations.AddField(
            model_name="occurrence",
            name="p_event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="occurrences",
                to="occurrences.PalvelutarjotinEvent",
                verbose_name="palvelutarjotin event",
            ),
        ),
    ]
