# Generated by Django 2.2.10 on 2020-05-27 09:03
from django.conf import settings
from django.db import migrations, models
from occurrences.models import Language


def add_default_languages(apps, schema_editor):
    for code, name in settings.LANGUAGES:
        Language.objects.create(id=code, name=name)


class Migration(migrations.Migration):
    dependencies = [
        ("occurrences", "0004_add_fields_to_occurrence"),
    ]

    operations = [
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=20, verbose_name="name")),
            ],
            options={"verbose_name": "language", "verbose_name_plural": "languages",},
        ),
        migrations.AddField(
            model_name="occurrence",
            name="languages",
            field=models.ManyToManyField(
                blank=True,
                related_name="occurrences",
                to="occurrences.Language",
                verbose_name="languages",
            ),
        ),
        migrations.RunPython(add_default_languages, migrations.RunPython.noop),
    ]
