# Generated by Django 2.2.10 on 2020-05-28 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("occurrences", "0005_add_languages_to_occurrence"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="palvelutarjotinevent",
            name="enrolment_end",
        ),
        migrations.AddField(
            model_name="palvelutarjotinevent",
            name="enrolment_end_days",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="enrolment end days"
            ),
        ),
    ]
