# Generated by Django 2.2.10 on 2020-06-12 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organisations", "0003_add_publisher_to_organisation"),
        ("occurrences", "0008_update_enrolment_unq_constraint"),
    ]

    operations = [
        migrations.AddField(
            model_name="palvelutarjotinevent",
            name="organisation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="p_event",
                to="organisations.Organisation",
                verbose_name="organisation",
            ),
        ),
    ]
