# Generated by Django 2.2.10 on 2020-06-25 08:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("occurrences", "0009_palvelutarjotinevent_organisation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="occurrence",
            name="organisation",
        ),
    ]
