# Generated by Django 2.2.10 on 2020-06-22 15:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("occurrences", "0010_remove_occurrence_organisation"),
    ]

    operations = [
        migrations.AddField(
            model_name="palvelutarjotinevent",
            name="contact_email",
            field=models.EmailField(
                blank=True, max_length=255, verbose_name="contact email"
            ),
        ),
        migrations.AddField(
            model_name="palvelutarjotinevent",
            name="contact_phone_number",
            field=models.CharField(
                blank=True, max_length=64, verbose_name="contact phone number"
            ),
        ),
    ]
