# Generated by Django 2.2.10 on 2020-07-02 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organisations", "0004_person_language"),
        ("occurrences", "0012_palvelutarjotinevent_contact_person"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrolment",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("email_sms", "email and sms"),
                    ("email", "email"),
                    ("sms", "sms"),
                ],
                default="email",
                max_length=250,
                verbose_name="notification type",
            ),
        ),
        migrations.AddField(
            model_name="enrolment",
            name="person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="organisations.Person",
                verbose_name="person",
            ),
        ),
        migrations.AddField(
            model_name="studygroup",
            name="amount_of_adult",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="amount of adult"
            ),
        ),
        migrations.AddField(
            model_name="studygroup",
            name="extra_needs",
            field=models.CharField(blank=True, max_length=1000, verbose_name="name"),
        ),
        migrations.AddField(
            model_name="studygroup",
            name="group_name",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="group name"
            ),
        ),
        migrations.AddField(
            model_name="studygroup",
            name="study_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("preschool", "preschool"),
                    ("grade_1", "first grade"),
                    ("grade_2", "second grade"),
                    ("grade_3", "third grade"),
                    ("grade_4", "fourth grade"),
                    ("grade_5", "fifth grade"),
                    ("grade_6", "sixth grade"),
                    ("grade_7", "seventh grade"),
                    ("grade_8", "eighth grade"),
                    ("grade_9", "ninth grade"),
                    ("grade_10", "tenth grade"),
                    ("secondary", "secondary"),
                ],
                max_length=255,
                verbose_name="study level",
            ),
        ),
    ]
