# Generated by Django 2.2.10 on 2020-07-03 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("occurrences", "0013_add_missing_fields_to_study_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrolment",
            name="status",
            field=models.CharField(
                choices=[
                    ("approved", "approved"),
                    ("pending", "pending"),
                    ("cancelled", "cancelled"),
                ],
                default="pending",
                max_length=255,
                verbose_name="status",
            ),
        ),
    ]
