# Generated by Django 2.2.13 on 2020-08-25 10:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("occurrences", "0014_enrolment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="occurrence",
            name="cancelled",
            field=models.BooleanField(default=False, verbose_name="cancelled"),
        ),
    ]
