# Generated by Django 2.2.13 on 2020-10-15 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("occurrences", "0015_occurrence_cancelled"),
    ]

    operations = [
        migrations.AddField(
            model_name="venuecustomdata",
            name="outdoor_activity",
            field=models.BooleanField(default=False, verbose_name="outdoor activity"),
        ),
    ]
