# Generated by Django 2.2.13 on 2020-10-15 11:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("occurrences", "0016_venuecustomdata_outdoor_activity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="occurrence",
            name="max_group_size",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="max group size"
            ),
        ),
        migrations.AlterField(
            model_name="occurrence",
            name="min_group_size",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="min group size"
            ),
        ),
    ]
