# Generated by Django 2.2.13 on 2020-10-16 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("occurrences", "0017_nullable_min_max_group_size"),
    ]

    operations = [
        migrations.RemoveField(model_name="occurrence", name="auto_acceptance",),
        migrations.AddField(
            model_name="palvelutarjotinevent",
            name="auto_acceptance",
            field=models.BooleanField(default=False, verbose_name="auto acceptance"),
        ),
    ]
