# Generated by Django 2.2.13 on 2020-12-17 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("occurrences", "0019_remove_palvelutarjotinevent_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="occurrence",
            name="seat_type",
            field=models.CharField(
                choices=[
                    ("children_count", "children count"),
                    ("enrolment_count", "enrolment count"),
                ],
                default="enrolment_count",
                max_length=64,
                verbose_name="seat type",
            ),
            preserve_default=False,
        ),
    ]
