# Generated by Django 2.2.13 on 2021-01-19 13:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("occurrences", "0020_occurrence_seat_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="palvelutarjotinevent",
            name="mandatory_additional_information",
            field=models.BooleanField(
                default=False, verbose_name="mandatory additional information"
            ),
        ),
    ]
