# Generated by Django 2.2.13 on 2021-01-14 14:22

import django.db.models.deletion
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("occurrences", "0021_palvelutarjotinevent_mandatory_additional_information"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudyLevel",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                (
                    "level",
                    models.PositiveIntegerField(
                        help_text="Used to make a hierarchy between study levels.",
                        verbose_name="level",
                    ),
                ),
            ],
            options={
                "ordering": ["level"],
                "verbose_name": "study level",
                "verbose_name_plural": "study levels",
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name="studygroup",
            name="study_levels",
            field=models.ManyToManyField(
                blank=True,
                related_name="study_groups",
                to="occurrences.StudyLevel",
                verbose_name="study levels",
            ),
        ),
        migrations.CreateModel(
            name="StudyLevelTranslation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        db_index=True, max_length=15, verbose_name="Language"
                    ),
                ),
                ("label", models.CharField(max_length=255, verbose_name="label")),
                (
                    "master",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="occurrences.StudyLevel",
                    ),
                ),
            ],
            options={
                "verbose_name": "study level Translation",
                "db_table": "occurrences_studylevel_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
        ),
    ]
