# Generated by Django 2.2.13 on 2021-01-15 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("occurrences", "0022_study_level_data"),
    ]

    operations = [
        # The old study_level field cannot be removed until data migration is done!
        migrations.RemoveField(model_name="studygroup", name="study_level",),
    ]
