# Generated by Django 2.2.13 on 2021-02-01 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("occurrences", "0024_study_group_cleaning"),
    ]

    operations = [
        migrations.AddField(
            model_name="palvelutarjotinevent",
            name="payment_instruction",
            field=models.TextField(blank=True, verbose_name="payment instruction"),
        ),
    ]
