# Generated by Django 2.2.13 on 2021-02-25 11:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("occurrences", "0026_remove_palvelutarjotinevent_payment_instruction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="palvelutarjotinevent",
            name="linked_event_id",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="linked event id"
            ),
        ),
    ]
