# Generated by Django 3.2.5 on 2021-07-14 07:44

import django.db.models.deletion
import parler.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("occurrences", "0030_add_new_study_level_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studyleveltranslation",
            name="master",
            field=parler.fields.TranslationsForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="translations",
                to="occurrences.studylevel",
            ),
        ),
        migrations.AlterField(
            model_name="venuecustomdatatranslation",
            name="master",
            field=parler.fields.TranslationsForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="translations",
                to="occurrences.venuecustomdata",
            ),
        ),
    ]
