# Generated by Django 3.2.5 on 2021-09-14 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("occurrences", "0031_auto_20210714_1044"),
    ]

    operations = [
        migrations.AddField(
            model_name="palvelutarjotinevent",
            name="external_enrolment_url",
            field=models.URLField(blank=True, null=True, verbose_name="enrolment url"),
        ),
    ]
