# Generated by Django 3.2.5 on 2021-11-16 11:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("occurrences", "0033_rename_studygroup_name_field_and_add_unit_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studygroup",
            name="unit_name",
            field=models.CharField(
                blank=True, max_length=1000, verbose_name="unit name"
            ),
        ),
    ]
