# Generated by Django 3.2.5 on 2021-12-02 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("occurrences", "0035_add_enrolment_updated_at_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studygroup",
            name="extra_needs",
            field=models.TextField(
                blank=True, max_length=1000, verbose_name="extra needs"
            ),
        ),
    ]
