# Generated by Django 3.2.13 on 2022-12-27 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("organisations", "0008_person_place_ids"),
        ("occurrences", "0037_palvelutarjotineventtranslation"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrolment",
            name="person_deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="person deleted at"
            ),
        ),
        migrations.AddField(
            model_name="studygroup",
            name="person_deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="person deleted at"
            ),
        ),
        migrations.AlterField(
            model_name="enrolment",
            name="person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="organisations.person",
                verbose_name="person",
            ),
        ),
        migrations.AlterField(
            model_name="studygroup",
            name="person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="organisations.person",
                verbose_name="person",
            ),
        ),
    ]
