# Generated by Django 3.2.13 on 2022-12-29 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0009_alter_user_managers"),
        ("occurrences", "0039_deletable_contact_info_support"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnrolleePersonalData",
            fields=[],
            options={
                "verbose_name": "Enrollee personal data",
                "verbose_name_plural": "Enrollee personal data",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("organisations.person",),
        ),
    ]
