# Generated by Django 3.2.16 on 2023-04-18 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0010_fix_user_manager"),
        ("occurrences", "0040_enrolleepersonaldata"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventQueueEnrolment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "person_deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="person deleted at"
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("email_sms", "email and sms"),
                            ("email", "email"),
                            ("sms", "sms"),
                        ],
                        default="email",
                        max_length=250,
                        verbose_name="notification type",
                    ),
                ),
                (
                    "enrolment_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="enrolment time"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "p_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="queued_enrolments",
                        to="occurrences.palvelutarjotinevent",
                        verbose_name="event",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="organisations.person",
                        verbose_name="person",
                    ),
                ),
                (
                    "study_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="queued_enrolments",
                        to="occurrences.studygroup",
                        verbose_name="study group",
                    ),
                ),
            ],
            options={
                "verbose_name": "event queue enrolment",
                "verbose_name_plural": "event queue enrolments",
            },
        ),
        migrations.AddConstraint(
            model_name="eventqueueenrolment",
            constraint=models.UniqueConstraint(
                fields=("study_group", "p_event"), name="unq_group_event"
            ),
        ),
    ]
