# Generated by Django 3.2.18 on 2023-12-11 10:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("occurrences", "0041_eventqueueenrolment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="enrolment",
            options={
                "ordering": ["occurrence", "enrolment_time"],
                "verbose_name": "enrolment",
                "verbose_name_plural": "enrolments",
            },
        ),
        migrations.AlterModelOptions(
            name="studygroup",
            options={
                "ordering": ["created_at"],
                "verbose_name": "study group",
                "verbose_name_plural": "study groups",
            },
        ),
    ]
