# Generated by Django 3.2.18 on 2024-04-11 06:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("occurrences", "0042_auto_20231211_1254"),
    ]

    operations = [
        migrations.AddField(
            model_name="palvelutarjotinevent",
            name="is_queueing_allowed",
            field=models.BooleanField(
                default=True, verbose_name="is queueing to event allowed?"
            ),
        ),
        migrations.AddField(
            model_name="studygroup",
            name="preferred_times",
            field=models.TextField(
                blank=True,
                help_text="Preferred times for the event",
                max_length=1000,
                verbose_name="preferred times",
            ),
        ),
        migrations.AddIndex(
            model_name="palvelutarjotinevent",
            index=models.Index(fields=["enrolment_start"], name="enrolment_start_idx"),
        ),
        migrations.AddIndex(
            model_name="palvelutarjotinevent",
            index=models.Index(
                fields=["is_queueing_allowed"], name="is_queueing_allowed_idx"
            ),
        ),
    ]
