# Generated by Django 4.2.20 on 2025-03-17 15:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("occurrences", "0043_add_is_queueing_allowed_and_preferred_times"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="studygroup",
            options={
                "ordering": ["created_at", "group_name"],
                "verbose_name": "study group",
                "verbose_name_plural": "study groups",
            },
        ),
    ]
