# Generated by Django 5.2.14 on 2026-05-28 12:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrolmentreport",
            name="is_part_of_cultural_route",
            field=models.BooleanField(
                default=False,
                help_text="Is enrolment part of a cultural route? True means yes, False means no or unknown.",
                verbose_name="is part of cultural route",
            ),
        ),
    ]
