# Generated by Django 2.2.10 on 2020-05-05 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0011_update_proxy_permissions"),
        ("organisations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="group",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="auth.Group",
                verbose_name="group",
            ),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="persons",
            field=models.ManyToManyField(
                blank=True,
                related_name="organisations",
                to="organisations.Person",
                verbose_name="persons",
            ),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="type",
            field=models.CharField(
                choices=[("user", "User"), ("provider", "Provider")],
                max_length=64,
                verbose_name="type",
            ),
        ),
    ]
