# Generated by Django 2.2.10 on 2020-06-10 13:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organisations", "0002_update_organisation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organisation",
            name="group",
        ),
        migrations.AddField(
            model_name="organisation",
            name="publisher_id",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="publisher id"
            ),
        ),
    ]
