# Generated by Django 2.2.10 on 2020-06-23 09:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organisations", "0003_add_publisher_to_organisation"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="language",
            field=models.CharField(
                default="fi", max_length=10, verbose_name="language"
            ),
        ),
    ]
