# Generated by Django 2.2.13 on 2021-06-30 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0004_person_language"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganisationProposal",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="description"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="phone number"
                    ),
                ),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organisations.Person",
                        verbose_name="applicant",
                    ),
                ),
            ],
            options={
                "verbose_name": "organisation proposal",
                "verbose_name_plural": "organisation proposals",
            },
        ),
    ]
