# Generated by Django 2.2.13 on 2021-07-05 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0005_organisationproposal"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_admin",
            field=models.BooleanField(default=False, verbose_name="admin status"),
        ),
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [
                    (
                        "can_administrate_user_permissions",
                        "Can administrate user permissions",
                    )
                ],
                "verbose_name": "user",
                "verbose_name_plural": "users",
            },
        ),
    ]
