# Generated by Django 3.2.5 on 2021-09-17 08:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0007_alter_user_first_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="place_ids",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=250),
                blank=True,
                default=list,
                size=None,
                verbose_name="own places",
            ),
        ),
    ]
