# Generated by Django 3.2.13 on 2022-12-29 23:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organisations", "0008_person_place_ids"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
