# Generated by Django 3.2.18 on 2023-09-18 11:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organisations", "0010_fix_user_manager"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisation",
            name="publisher_id",
            field=models.CharField(max_length=255, verbose_name="publisher id"),
        ),
        migrations.AddConstraint(
            model_name="organisation",
            constraint=models.CheckConstraint(
                check=models.Q(("publisher_id__regex", "^\\s*$"), _negated=True),
                name="publisher_id_neq_empty_or_whitespace_only_string",
            ),
        ),
    ]
