# Generated by Django 3.2.18 on 2023-12-11 10:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organisations", "0011_enforce_non_empty_publisher_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="person",
            options={
                "ordering": ["name", "user"],
                "verbose_name": "person",
                "verbose_name_plural": "persons",
            },
        ),
    ]
