# Generated by Django 5.2.7 on 2025-10-06 13:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organisations", "0015_add_ordering_and_indices_to_organisations"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_api_use",
            field=models.DateField(
                blank=True, null=True, verbose_name="Latest API token usage date"
            ),
        ),
    ]
