name: Build & Production
on:
  push:
    tags:
      - 'release-*'

env:
  CONTAINER_REGISTRY: ghcr.io
  CONTAINER_REGISTRY_USER: ${{ secrets.GHCR_CONTAINER_REGISTRY_USER }}
  CONTAINER_REGISTRY_PASSWORD: ${{ secrets.GHCR_TOKEN }}
  CONTAINER_REGISTRY_REPO: ghcr.io/city-of-helsinki/${{ github.event.repository.name }}
  REPO_NAME: ${{ github.event.repository.name }}
  KUBECONFIG_RAW: ${{ secrets.KUBECONFIG_RAW_STABLE }}
  BUILD_ARTIFACT_FOLDER: 'build_artifacts'
  SERVICE_ARTIFACT_FOLDER: 'service_artifacts'
  APP_MIGRATE_COMMAND: /app/.prod/on_deploy.sh
  K8S_REQUEST_CPU: 70m
  K8S_REQUEST_RAM: 200Mi
  K8S_LIMIT_CPU: 200m
  K8S_LIMIT_RAM: 300Mi
  K8S_REPLICACOUNT: 2

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v2
      - name: Build
        uses: andersinno/kolga-build-action@v2

  production:
    runs-on: ubuntu-latest
    needs: build
    name: Production
    steps:
      - uses: actions/checkout@v2
      - uses: andersinno/kolga-setup-action@v2

      - name: Deploy
        uses: andersinno/kolga-deploy-action@v2
        with:
          track: 'stable'
        env:
          K8S_NAMESPACE: ${{ secrets.K8S_NAMESPACE_STABLE }}
          K8S_ADDITIONAL_HOSTNAMES: ${{ secrets.K8S_ADDITIONAL_HOSTNAMES }}
          ENVIRONMENT_URL: https://${{ secrets.ENVIRONMENT_URL_STABLE }}
          K8S_SECRET_ENVIRONMENT_URL: https://${{ secrets.ENVIRONMENT_URL_STABLE }}
          K8S_SECRET_ALLOWED_HOSTS: "*"
          K8S_SECRET_CORS_ORIGIN_ALLOW_ALL: 1
          K8S_SECRET_SECRET_KEY: ${{ secrets.GH_PRODUCTION_DJANGO_SECRET_KEY }}
          K8S_SECRET_SKIP_DATABASE_CHECK: 1
          K8S_SECRET_TOKEN_AUTH_AUTHSERVER_URL: "https://api.hel.fi/sso/openid"
          K8S_SECRET_ILMOITIN_QUEUE_NOTIFICATIONS: 1
          K8S_SECRET_MAIL_MAILGUN_KEY: ${{ secrets.SECRET_GH_PROD_MAILGUN_API_KEY }}
          K8S_SECRET_MAIL_MAILGUN_DOMAIN: "mail.hel.ninja"
          K8S_SECRET_MAIL_MAILGUN_API: "https://api.eu.mailgun.net/v3"
          K8S_SECRET_MAILER_EMAIL_BACKEND: "anymail.backends.mailgun.EmailBackend"
          K8S_SECRET_DEFAULT_FROM_EMAIL: "no-reply@hel.ninja"
          K8S_SECRET_SENTRY_DSN: ${{ secrets.GH_SENTRY_DNS }}
          K8S_SECRET_SENTRY_ENVIRONMENT: "production"
          K8S_SECRET_ENABLE_GRAPHIQL: 0
          K8S_SECRET_LINKED_EVENTS_API_ROOT: "https://api.hel.fi/linkedevents/v1/"
          K8S_SECRET_LINKED_EVENTS_API_KEY: ${{ secrets.GH_PRODUCTION_LINKED_EVENTS_API_KEY }}
          K8S_SECRET_LINKED_EVENTS_DATA_SOURCE: ${{ secrets.LINKED_EVENTS_DATA_SOURCE }}
          K8S_SECRET_NEIGHBORHOOD_API_ROOT: "https://kartta.hel.fi/ws/geoserver/avoindata/wfs"
          K8S_SECRET_NOTIFICATION_SERVICE_API_TOKEN: ${{ secrets.GH_PRODUCTION_NS_API_TOKEN }}
          K8S_SECRET_NOTIFICATION_SERVICE_API_URL: ${{ secrets.GH_PRODUCTION_NS_API_URL }}
          K8S_SECRET_CAPTCHA_ENABLED: ${{ secrets.GH_PRODUCTION_CAPTCHA_ENABLED }}
          K8S_SECRET_RECAPTCHA_SECRET_KEY: ${{ secrets.GH_PRODUCTION_RECAPTCHA_SECRET_KEY }}
          K8S_SECRET_KEYWORD_SET_CATEGORY_ID: ${{ secrets.GH_PRODUCTION_KEYWORD_SET_CATEGORY_ID }}
          K8S_SECRET_KEYWORD_SET_ADDITIONAL_CRITERIA_ID: ${{ secrets.GH_PRODUCTION_KEYWORD_SET_ADDITIONAL_CRITERIA_ID }}
          K8S_SECRET_KEYWORD_SET_TARGET_GROUP_ID: ${{ secrets.GH_PRODUCTION_KEYWORD_SET_TARGET_GROUP_ID }}
          K8S_SECRET_KULTUS_PROVIDER_UI_BASE_URL: "https://provider.kultus.fi/"
          K8S_SECRET_KULTUS_TEACHER_UI_BASE_URL: "https://beta.kultus.fi/"
          K8S_SECRET_CREATE_SUPERUSER: 0
          K8S_SECRET_ENABLE_SUMMARY_REPORT: 1
          K8S_SECRET_TOKEN_AUTH_ACCEPTED_AUDIENCE: ${{ secrets.TOKEN_AUTH_ACCEPTED_AUDIENCE }}
          K8S_SECRET_TOKEN_AUTH_ACCEPTED_SCOPE_PREFIX: ${{ secrets.TOKEN_AUTH_ACCEPTED_SCOPE }}
          K8S_SECRET_DATABASE_HOST: ${{ secrets.K8S_SECRET_DATABASE_HOST_STABLE }}
          K8S_SECRET_DATABASE_URL: ${{ secrets.K8S_SECRET_DATABASE_URL_STABLE }}
          K8S_SECRET_DATABASE_PORT: ${{ secrets.K8S_SECRET_DATABASE_PORT_STABLE }}
          K8S_SECRET_DATABASE_DB: ${{ secrets.K8S_SECRET_DATABASE_DB_STABLE }}
          K8S_SECRET_DATABASE_USERNAME: ${{ secrets.K8S_SECRET_DATABASE_USERNAME_STABLE }}
          K8S_SECRET_DATABASE_PASSWORD: ${{ secrets.K8S_SECRET_DATABASE_PASSWORD_STABLE }}

      - name: Deploy Send Mail Cronjob
        uses: City-of-Helsinki/setup-cronjob-action@main
        with:
          image_repository: ghcr.io/city-of-helsinki/${{ github.event.repository.name }}
          image_tag:  ${{ github.sha }}
          secret_name: "project-palvelutarjotin-secret"
          name: "send-mail"
          kubeconfig_raw: ${{ secrets.KUBECONFIG_RAW_STABLE}}
          target_namespace: ${{ secrets.K8S_NAMESPACE_STABLE }}
          schedule: '* * * * *' # once per 1 minute
          command: "{/app/manage.py}"
          args: "{send_mail}"

      - name: Deploy Retry Deferred Mail Cronjob
        uses: City-of-Helsinki/setup-cronjob-action@main
        with:
          image_repository: ghcr.io/city-of-helsinki/${{ github.event.repository.name }}
          image_tag:  ${{ github.sha }}
          secret_name: "project-palvelutarjotin-secret"
          name: "retry-deferred"
          kubeconfig_raw: ${{ secrets.KUBECONFIG_RAW_STABLE}}
          target_namespace: ${{ secrets.K8S_NAMESPACE_STABLE }}
          schedule: '*/20 * * * *' # once per 20 minutes
          command: "{/app/manage.py}"
          args: "{retry_deferred}"

      - name: Deploy Send Enrolment Summary Email Cronjob
        uses: City-of-Helsinki/setup-cronjob-action@main
        with:
          image_repository: ghcr.io/city-of-helsinki/${{ github.event.repository.name }}
          image_tag:  ${{ github.sha }}
          secret_name: "project-palvelutarjotin-secret"
          name: "send-enrolment-summary"
          kubeconfig_raw: ${{ secrets.KUBECONFIG_RAW_STABLE}}
          target_namespace: ${{ secrets.K8S_NAMESPACE_STABLE }}
          schedule: '0 8 * * *' # every day 8 AM
          command: "{/app/manage.py}"
          args: "{send_enrolment_summary}"

      - name: Deploy Clean Invalid Token Cronjob
        uses: City-of-Helsinki/setup-cronjob-action@main
        with:
          image_repository: ghcr.io/city-of-helsinki/${{ github.event.repository.name }}
          image_tag:  ${{ github.sha }}
          secret_name: "project-palvelutarjotin-secret"
          name: "clean-invalid-tokens"
          kubeconfig_raw: ${{ secrets.KUBECONFIG_RAW_STABLE}}
          target_namespace: ${{ secrets.K8S_NAMESPACE_STABLE }}
          schedule: '0 8 * * *' # every day 8 AM
          command: "{/app/manage.py}"
          args: "{clean_invalid_tokens}"

